// This file is generated. Do not edit.
#import "AMQMethodMap.h"
#import "AMQMethods.h"

@implementation AMQMethodMap
+ (NSDictionary *)methodMap {
    return @{@[@(10), @(10)] : [AMQConnectionStart class],
             @[@(10), @(11)] : [AMQConnectionStartOk class],
             @[@(10), @(20)] : [AMQConnectionSecure class],
             @[@(10), @(21)] : [AMQConnectionSecureOk class],
             @[@(10), @(30)] : [AMQConnectionTune class],
             @[@(10), @(31)] : [AMQConnectionTuneOk class],
             @[@(10), @(40)] : [AMQConnectionOpen class],
             @[@(10), @(41)] : [AMQConnectionOpenOk class],
             @[@(10), @(50)] : [AMQConnectionClose class],
             @[@(10), @(51)] : [AMQConnectionCloseOk class],
             @[@(10), @(60)] : [AMQConnectionBlocked class],
             @[@(10), @(61)] : [AMQConnectionUnblocked class],
             @[@(20), @(10)] : [AMQChannelOpen class],
             @[@(20), @(11)] : [AMQChannelOpenOk class],
             @[@(20), @(20)] : [AMQChannelFlow class],
             @[@(20), @(21)] : [AMQChannelFlowOk class],
             @[@(20), @(40)] : [AMQChannelClose class],
             @[@(20), @(41)] : [AMQChannelCloseOk class],
             @[@(40), @(10)] : [AMQExchangeDeclare class],
             @[@(40), @(11)] : [AMQExchangeDeclareOk class],
             @[@(40), @(20)] : [AMQExchangeDelete class],
             @[@(40), @(21)] : [AMQExchangeDeleteOk class],
             @[@(40), @(30)] : [AMQExchangeBind class],
             @[@(40), @(31)] : [AMQExchangeBindOk class],
             @[@(40), @(40)] : [AMQExchangeUnbind class],
             @[@(40), @(51)] : [AMQExchangeUnbindOk class],
             @[@(50), @(10)] : [AMQQueueDeclare class],
             @[@(50), @(11)] : [AMQQueueDeclareOk class],
             @[@(50), @(20)] : [AMQQueueBind class],
             @[@(50), @(21)] : [AMQQueueBindOk class],
             @[@(50), @(50)] : [AMQQueueUnbind class],
             @[@(50), @(51)] : [AMQQueueUnbindOk class],
             @[@(50), @(30)] : [AMQQueuePurge class],
             @[@(50), @(31)] : [AMQQueuePurgeOk class],
             @[@(50), @(40)] : [AMQQueueDelete class],
             @[@(50), @(41)] : [AMQQueueDeleteOk class],
             @[@(60), @(10)] : [AMQBasicQos class],
             @[@(60), @(11)] : [AMQBasicQosOk class],
             @[@(60), @(20)] : [AMQBasicConsume class],
             @[@(60), @(21)] : [AMQBasicConsumeOk class],
             @[@(60), @(30)] : [AMQBasicCancel class],
             @[@(60), @(31)] : [AMQBasicCancelOk class],
             @[@(60), @(40)] : [AMQBasicPublish class],
             @[@(60), @(50)] : [AMQBasicReturn class],
             @[@(60), @(60)] : [AMQBasicDeliver class],
             @[@(60), @(70)] : [AMQBasicGet class],
             @[@(60), @(71)] : [AMQBasicGetOk class],
             @[@(60), @(72)] : [AMQBasicGetEmpty class],
             @[@(60), @(80)] : [AMQBasicAck class],
             @[@(60), @(90)] : [AMQBasicReject class],
             @[@(60), @(100)] : [AMQBasicRecoverAsync class],
             @[@(60), @(110)] : [AMQBasicRecover class],
             @[@(60), @(111)] : [AMQBasicRecoverOk class],
             @[@(60), @(120)] : [AMQBasicNack class],
             @[@(90), @(10)] : [AMQTxSelect class],
             @[@(90), @(11)] : [AMQTxSelectOk class],
             @[@(90), @(20)] : [AMQTxCommit class],
             @[@(90), @(21)] : [AMQTxCommitOk class],
             @[@(90), @(30)] : [AMQTxRollback class],
             @[@(90), @(31)] : [AMQTxRollbackOk class],
             @[@(85), @(10)] : [AMQConfirmSelect class],
             @[@(85), @(11)] : [AMQConfirmSelectOk class]};
}
@end
