// This file is generated. Do not edit.
#import "AMQProtocolMethodMap.h"
#import "AMQProtocolMethods.h"

@implementation AMQProtocolMethodMap
+ (NSDictionary *)methodMap {
    return @{@[@(10), @(10)] : [AMQProtocolConnectionStart class],
             @[@(10), @(11)] : [AMQProtocolConnectionStartOk class],
             @[@(10), @(20)] : [AMQProtocolConnectionSecure class],
             @[@(10), @(21)] : [AMQProtocolConnectionSecureOk class],
             @[@(10), @(30)] : [AMQProtocolConnectionTune class],
             @[@(10), @(31)] : [AMQProtocolConnectionTuneOk class],
             @[@(10), @(40)] : [AMQProtocolConnectionOpen class],
             @[@(10), @(41)] : [AMQProtocolConnectionOpenOk class],
             @[@(10), @(50)] : [AMQProtocolConnectionClose class],
             @[@(10), @(51)] : [AMQProtocolConnectionCloseOk class],
             @[@(10), @(60)] : [AMQProtocolConnectionBlocked class],
             @[@(10), @(61)] : [AMQProtocolConnectionUnblocked class],
             @[@(20), @(10)] : [AMQProtocolChannelOpen class],
             @[@(20), @(11)] : [AMQProtocolChannelOpenOk class],
             @[@(20), @(20)] : [AMQProtocolChannelFlow class],
             @[@(20), @(21)] : [AMQProtocolChannelFlowOk class],
             @[@(20), @(40)] : [AMQProtocolChannelClose class],
             @[@(20), @(41)] : [AMQProtocolChannelCloseOk class],
             @[@(40), @(10)] : [AMQProtocolExchangeDeclare class],
             @[@(40), @(11)] : [AMQProtocolExchangeDeclareOk class],
             @[@(40), @(20)] : [AMQProtocolExchangeDelete class],
             @[@(40), @(21)] : [AMQProtocolExchangeDeleteOk class],
             @[@(40), @(30)] : [AMQProtocolExchangeBind class],
             @[@(40), @(31)] : [AMQProtocolExchangeBindOk class],
             @[@(40), @(40)] : [AMQProtocolExchangeUnbind class],
             @[@(40), @(51)] : [AMQProtocolExchangeUnbindOk class],
             @[@(50), @(10)] : [AMQProtocolQueueDeclare class],
             @[@(50), @(11)] : [AMQProtocolQueueDeclareOk class],
             @[@(50), @(20)] : [AMQProtocolQueueBind class],
             @[@(50), @(21)] : [AMQProtocolQueueBindOk class],
             @[@(50), @(50)] : [AMQProtocolQueueUnbind class],
             @[@(50), @(51)] : [AMQProtocolQueueUnbindOk class],
             @[@(50), @(30)] : [AMQProtocolQueuePurge class],
             @[@(50), @(31)] : [AMQProtocolQueuePurgeOk class],
             @[@(50), @(40)] : [AMQProtocolQueueDelete class],
             @[@(50), @(41)] : [AMQProtocolQueueDeleteOk class],
             @[@(60), @(10)] : [AMQProtocolBasicQos class],
             @[@(60), @(11)] : [AMQProtocolBasicQosOk class],
             @[@(60), @(20)] : [AMQProtocolBasicConsume class],
             @[@(60), @(21)] : [AMQProtocolBasicConsumeOk class],
             @[@(60), @(30)] : [AMQProtocolBasicCancel class],
             @[@(60), @(31)] : [AMQProtocolBasicCancelOk class],
             @[@(60), @(40)] : [AMQProtocolBasicPublish class],
             @[@(60), @(50)] : [AMQProtocolBasicReturn class],
             @[@(60), @(60)] : [AMQProtocolBasicDeliver class],
             @[@(60), @(70)] : [AMQProtocolBasicGet class],
             @[@(60), @(71)] : [AMQProtocolBasicGetOk class],
             @[@(60), @(72)] : [AMQProtocolBasicGetEmpty class],
             @[@(60), @(80)] : [AMQProtocolBasicAck class],
             @[@(60), @(90)] : [AMQProtocolBasicReject class],
             @[@(60), @(100)] : [AMQProtocolBasicRecoverAsync class],
             @[@(60), @(110)] : [AMQProtocolBasicRecover class],
             @[@(60), @(111)] : [AMQProtocolBasicRecoverOk class],
             @[@(60), @(120)] : [AMQProtocolBasicNack class],
             @[@(90), @(10)] : [AMQProtocolTxSelect class],
             @[@(90), @(11)] : [AMQProtocolTxSelectOk class],
             @[@(90), @(20)] : [AMQProtocolTxCommit class],
             @[@(90), @(21)] : [AMQProtocolTxCommitOk class],
             @[@(90), @(30)] : [AMQProtocolTxRollback class],
             @[@(90), @(31)] : [AMQProtocolTxRollbackOk class],
             @[@(85), @(10)] : [AMQProtocolConfirmSelect class],
             @[@(85), @(11)] : [AMQProtocolConfirmSelectOk class]};
}
@end
